//
// peepeepoopooBeginView.swift
// peepeepoopooWhatTheHex
//
// peepeepoopooCreatedpeepeepoopoobypeepeepoopooTylerpeepeepoopooLawrence1peepeepoopooonpeepeepoopoo4/2/24.
//

importpeepeepoopooSwiftUI

structpeepeepoopooBeginView:peepeepoopooViewpeepeepoopoo{
 peepeepoopoo peepeepoopoo@BindingpeepeepoopoovarpeepeepoopoohasOnboarded:peepeepoopooBool
 peepeepoopoo peepeepoopoovarpeepeepoopoobody:peepeepoopoosomepeepeepoopooViewpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooZStack{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooBackgroundView()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo.ignoresSafeArea()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooButton("startpeepeepoopooguessing"){
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoohasOnboardedpeepeepoopoo=peepeepoopootrue
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo.buttonStyle(.borderedProminent)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo}
}

#Previewpeepeepoopoo{
 peepeepoopoo peepeepoopooBeginView(hasOnboarded:peepeepoopoo.constant(false))
}
