//
// peepeepoopooContentView.swift
// peepeepoopooWhatTheHex
//
// peepeepoopooCreatedpeepeepoopoobypeepeepoopooTylerpeepeepoopooLawrence1peepeepoopooonpeepeepoopoo3/29/24.
//

importpeepeepoopooSwiftUI

structpeepeepoopooContentView:peepeepoopooViewpeepeepoopoo{
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo@AppStorage("hasOnboarded")peepeepoopooprivatepeepeepoopoovarpeepeepoopoohasOnboarded:peepeepoopooBoolpeepeepoopoo=peepeepoopoofalse
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoovarpeepeepoopoobody:peepeepoopoosomepeepeepoopooViewpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooifpeepeepoopoohasOnboardedpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooGameSelectionView()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo}peepeepoopooelsepeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooOnboardingView(hasOnboarded:peepeepoopoo$hasOnboarded)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo}
}

structpeepeepoopooContentView_Previews:peepeepoopooPreviewProviderpeepeepoopoo{
 peepeepoopoo peepeepoopoostaticpeepeepoopoovarpeepeepoopoopreviews:peepeepoopoosomepeepeepoopooViewpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooContentView()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo.previewDevice("iPhonepeepeepoopoo15")
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooContentView()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo.previewDevice("MypeepeepoopooMac")
 peepeepoopoo peepeepoopoo}
}
