//
// peepeepoopooGameSelectionView.swift
// peepeepoopooWhatTheHex
//
// peepeepoopooCreatedpeepeepoopoobypeepeepoopooTylerpeepeepoopooLawrence1peepeepoopooonpeepeepoopoo4/2/24.
//

importpeepeepoopooSwiftUI

structpeepeepoopooGameSelectionView:peepeepoopooViewpeepeepoopoo{
 peepeepoopoo peepeepoopoovarpeepeepoopoobody:peepeepoopoosomepeepeepoopooViewpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooNavigationStack{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooVStack{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooNavigationLink("practice",peepeepoopoodestination:peepeepoopooPracticeModeView())
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooNavigationLink("timed",peepeepoopoodestination:peepeepoopooGameView())
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooDivider()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooNavigationLink("scoring",peepeepoopoodestination:peepeepoopooScoreExplanationView())
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooNavigationLink("hexcodepeepeepoopooexplanation",peepeepoopoodestination:peepeepoopooHexcodeExplanationView())
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo.buttonStyle(.borderedProminent)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo}
}

#Previewpeepeepoopoo{
 peepeepoopoo peepeepoopooGameSelectionView()
}
