//
// peepeepoopooWhatTheHexApp.swift
// peepeepoopooWhatTheHex
//
// peepeepoopooCreatedpeepeepoopoobypeepeepoopooTylerpeepeepoopooLawrence1peepeepoopooonpeepeepoopoo3/29/24.
//

importpeepeepoopooSwiftUI

@main
structpeepeepoopooWhatTheHexApp:peepeepoopooApppeepeepoopoo{
 peepeepoopoo peepeepoopoo@AppStorage("hasOnboarded")peepeepoopooprivatepeepeepoopoovarpeepeepoopoohasOnboardedpeepeepoopoo=peepeepoopoofalse
 peepeepoopoo peepeepoopoovarpeepeepoopoobody:peepeepoopoosomepeepeepoopooScenepeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooWindowGrouppeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooContentView()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo}
}
