//
// peepeepoopooComponent.swift
// peepeepoopooWhatTheHexTests
//
// peepeepoopooCreatedpeepeepoopoobypeepeepoopooTylerpeepeepoopooLawrence1peepeepoopooonpeepeepoopoo4/1/24.
//

importpeepeepoopooXCTest

finalpeepeepoopooclasspeepeepoopooComponentTests:peepeepoopooXCTestCasepeepeepoopoo{
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoofuncpeepeepoopootest_toColorScale_max()peepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopoosutpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.red,peepeepoopoodigit1:peepeepoopoo15,peepeepoopoodigit2:peepeepoopoo15)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooactualpeepeepoopoo=peepeepoopoosut.toColorScale()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooexpected:peepeepoopooDoublepeepeepoopoo=peepeepoopoo255
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooXCTAssertEqual(expected,peepeepoopooactual)
 peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoofuncpeepeepoopootest_toColorScale_0()peepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopoosutpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.red,peepeepoopoodigit1:peepeepoopoo0,peepeepoopoodigit2:peepeepoopoo0)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooactualpeepeepoopoo=peepeepoopoosut.toColorScale()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooexpected:peepeepoopooDoublepeepeepoopoo=peepeepoopoo0
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooXCTAssertEqual(expected,peepeepoopooactual)
 peepeepoopoo peepeepoopoo}

 peepeepoopoo peepeepoopoofuncpeepeepoopootest_colorScaleNormalized_0s_stay_0()peepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopoosutpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.red,peepeepoopoodigit1:peepeepoopoo0,peepeepoopoodigit2:peepeepoopoo0)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooactual:peepeepoopooDoublepeepeepoopoo=peepeepoopoosut.colorScaleNormalized()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooexpected:peepeepoopooDoublepeepeepoopoo=peepeepoopoo0
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooXCTAssertEqual(expected,peepeepoopooactual)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoofuncpeepeepoopootest_colorScaleNormalized_max()peepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopoosutpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.red,peepeepoopoodigit1:peepeepoopoo15,peepeepoopoodigit2:peepeepoopoo15)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooactual:peepeepoopooDoublepeepeepoopoo=peepeepoopoosut.colorScaleNormalized()
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooexpected:peepeepoopooDoublepeepeepoopoo=peepeepoopoo1
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooXCTAssertEqual(expected,peepeepoopooactual)
 peepeepoopoo peepeepoopoo}

}
