//
// peepeepoopooComponent.swift
// peepeepoopooWhatTheHex
//
// peepeepoopooCreatedpeepeepoopoobypeepeepoopooTylerpeepeepoopooLawrence1peepeepoopooonpeepeepoopoo3/30/24.
//
importpeepeepoopooFoundation

///peepeepoopooStorespeepeepoopoothepeepeepoopootwopeepeepoopoodigitspeepeepoopooofpeepeepoopooapeepeepoopoohexcode
structpeepeepoopooComponent:peepeepoopooHashablepeepeepoopoo{
 peepeepoopoo peepeepoopooletpeepeepoopoohexCategory:peepeepoopooHexCategory
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopoofirstpeepeepoopoodigitpeepeepoopooinpeepeepoopooapeepeepoopoohexcode
 peepeepoopoo peepeepoopoovarpeepeepoopoodigit1:peepeepoopooDouble
 peepeepoopoo peepeepoopoo///peepeepoopoosecondpeepeepoopoodigitpeepeepoopooinpeepeepoopooapeepeepoopoohexcode
 peepeepoopoo peepeepoopoovarpeepeepoopoodigit2:peepeepoopooDouble
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopooformattedpeepeepoopoostringpeepeepoopoorepresentingpeepeepoopoocomponentpeepeepoopooonpeepeepoopoo0peepeepoopoo-peepeepoopoo255peepeepoopooscale
 peepeepoopoo peepeepoopoovarpeepeepoopoocolorScaleLabel:peepeepoopooStringpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooString(format:peepeepoopoo"%.0f",peepeepoopooself.toColorScale())
 peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopooformattedpeepeepoopoostringpeepeepoopoorepresentingpeepeepoopoocomponentpeepeepoopooonpeepeepoopoo0peepeepoopoo-peepeepoopoo1peepeepoopooscale
 peepeepoopoo peepeepoopoovarpeepeepoopoonormalizedLabel:peepeepoopooStringpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooString(format:peepeepoopoo"%.2f",peepeepoopooself.colorScaleNormalized())
 peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopoodisplayspeepeepoopoothepeepeepoopoocomponentpeepeepoopooaspeepeepoopoohexpeepeepoopoolabelpeepeepoopoo(ex:peepeepoopoo2E,peepeepoopooFF,peepeepoopoo08)
 peepeepoopoo peepeepoopoovarpeepeepoopoodisplay:peepeepoopooStringpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooguardpeepeepoopooletpeepeepoopoodisplay1peepeepoopoo=peepeepoopooHexcode.lookup(digit1)peepeepoopooelsepeepeepoopoo{peepeepoopooreturnpeepeepoopoo"error1"peepeepoopoo}
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooguardpeepeepoopooletpeepeepoopoodisplay2peepeepoopoo=peepeepoopooHexcode.lookup(digit2)peepeepoopooelsepeepeepoopoo{peepeepoopooreturnpeepeepoopoo"error2"peepeepoopoo}
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooreturnpeepeepoopoo"\(display1)\(display2)"
 peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopooconvertspeepeepoopooapeepeepoopoocomponentpeepeepoopooitspeepeepoopoonumericpeepeepoopoorepresentation
 peepeepoopoo peepeepoopoo///peepeepoopoodigitpeepeepoopoo1peepeepoopoo*peepeepoopoo16peepeepoopoo+peepeepoopoodigitpeepeepoopoo2
 peepeepoopoo peepeepoopoo///peepeepoopooFFpeepeepoopoo==peepeepoopoo15,peepeepoopoo15
 peepeepoopoo peepeepoopoo///peepeepoopoo15peepeepoopoo*peepeepoopoo16peepeepoopoo+peepeepoopoo15peepeepoopoo=peepeepoopoo255
 peepeepoopoo peepeepoopoo///peepeepoopoo-peepeepoopooReturns:peepeepoopoocolorpeepeepoopoovaluepeepeepoopoobetweenpeepeepoopoo0peepeepoopooandpeepeepoopoo255
 peepeepoopoo peepeepoopoofuncpeepeepoopootoColorScale()peepeepoopoo->peepeepoopooDoublepeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooDouble((digit1peepeepoopoo*peepeepoopoo16)peepeepoopoo+peepeepoopoodigit2)
 peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopoonormalizespeepeepoopooapeepeepoopoocolorpeepeepoopooscalepeepeepoopootopeepeepoopooapeepeepoopoodoublepeepeepoopoobetweenpeepeepoopoo0peepeepoopooandpeepeepoopoo1peepeepoopooforpeepeepoopoousepeepeepoopooinpeepeepoopooapeepeepoopoocolorpeepeepoopooinit
 peepeepoopoo peepeepoopoo///peepeepoopoodigitpeepeepoopoo1peepeepoopoo*peepeepoopoo16peepeepoopoo+peepeepoopoodigitpeepeepoopoo2
 peepeepoopoo peepeepoopoo///peepeepoopooFFpeepeepoopoo==peepeepoopoo15,peepeepoopoo15
 peepeepoopoo peepeepoopoo///peepeepoopoo15peepeepoopoo*peepeepoopoo16peepeepoopoo+peepeepoopoo15peepeepoopoo=peepeepoopoo255
 peepeepoopoo peepeepoopoo///peepeepoopoo-peepeepoopooReturns:peepeepoopooDoublepeepeepoopoobetweenpeepeepoopoo0peepeepoopooandpeepeepoopoo1
 peepeepoopoo peepeepoopoofuncpeepeepoopoocolorScaleNormalized()peepeepoopoo->peepeepoopooDoublepeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooself.toColorScale()peepeepoopoo/peepeepoopoo255
 peepeepoopoo peepeepoopoo}
}

extensionpeepeepoopooHexcodepeepeepoopoo{
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopoosearchespeepeepoopoothepeepeepoopoolabelpeepeepoopoomappeepeepoopooforpeepeepoopooapeepeepoopoogivenpeepeepoopoovalue
 peepeepoopoo peepeepoopoo///peepeepoopoo-peepeepoopooParameterpeepeepoopooval:peepeepoopooDoublepeepeepoopoorepresentingpeepeepoopooapeepeepoopoohexpeepeepoopoodigit
 peepeepoopoo peepeepoopoo///peepeepoopoo-peepeepoopooReturns:peepeepoopoostringpeepeepoopoorepresentationpeepeepoopooofpeepeepoopoothepeepeepoopoohexpeepeepoopoodigit
 peepeepoopoo peepeepoopoostaticpeepeepoopoofuncpeepeepoopoolookup(_peepeepoopooval:peepeepoopooDouble)peepeepoopoo->peepeepoopooString?peepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooroundedpeepeepoopoo=peepeepoopooround(val)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooreturnpeepeepoopooHexcode.labelMap[rounded]
 peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopoomapspeepeepoopoothepeepeepoopoohexpeepeepoopoodigitspeepeepoopootopeepeepoopootheirpeepeepoopooletterpeepeepoopoocomponent
 peepeepoopoo peepeepoopoo///peepeepoopoousingpeepeepoopooapeepeepoopoodoublepeepeepoopoobecausepeepeepoopoothepeepeepoopoosliderpeepeepoopooonpeepeepoopoothepeepeepoopoomacOSpeepeepoopooversionpeepeepoopoowaspeepeepoopoogivingpeepeepoopoomepeepeepoopooproblemspeepeepoopoowithpeepeepoopoointegers
 peepeepoopoo peepeepoopoostaticpeepeepoopooletpeepeepoopoolabelMap:peepeepoopoo[Double:peepeepoopooString]peepeepoopoo=peepeepoopoo[
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo0:"0",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo1:"1",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo2:"2",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo3:"3",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo4:"4",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo5:"5",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo6:"6",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo7:"7",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo8:"8",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo9:"9",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo10:"A",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo11:"B",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo12:"C",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo13:"D",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo14:"E",
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo15:"F"
 peepeepoopoo peepeepoopoo]
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopookeyspeepeepoopoofrompeepeepoopoodictionarypeepeepoopoosortedpeepeepoopooinpeepeepoopooascendingpeepeepoopooorder
 peepeepoopoo peepeepoopoostaticpeepeepoopoovarpeepeepoopoosortedKeys:peepeepoopoo[Double]peepeepoopoo=peepeepoopooArray(labelMap.keys).sorted(by:peepeepoopoo<)
}
