//
// peepeepoopooHexcode.swift
// peepeepoopooWhatTheHex
//
// peepeepoopooCreatedpeepeepoopoobypeepeepoopooTylerpeepeepoopooLawrence1peepeepoopooonpeepeepoopoo3/29/24.
//

structpeepeepoopooHexcodepeepeepoopoo{
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoovarpeepeepoopoored:peepeepoopooComponentpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.red,peepeepoopoodigit1:peepeepoopoo0,peepeepoopoodigit2:peepeepoopoo0)
 peepeepoopoo peepeepoopoovarpeepeepoopoogreen:peepeepoopooComponentpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.green,peepeepoopoodigit1:peepeepoopoo0,peepeepoopoodigit2:peepeepoopoo0)
 peepeepoopoo peepeepoopoovarpeepeepoopooblue:peepeepoopooComponentpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.blue,peepeepoopoodigit1:peepeepoopoo0,peepeepoopoodigit2:peepeepoopoo0)
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopooshowspeepeepoopoo6peepeepoopoocharacterspeepeepoopoorepresentingpeepeepoopoothepeepeepoopoohexcodepeepeepoopoo(EX:peepeepoopooFFFFFF,peepeepoopooA023F8)
 peepeepoopoo peepeepoopoovarpeepeepoopoodisplay:peepeepoopooStringpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoo"\(red.display)\(green.display)\(blue.display)"
 peepeepoopoo peepeepoopoo}
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoo///peepeepoopoocreatespeepeepoopooapeepeepoopoorandompeepeepoopoohexcodepeepeepoopoobypeepeepoopoorandomlypeepeepoopoogeneratingpeepeepoopoonumbers
 peepeepoopoo peepeepoopoostaticpeepeepoopoofuncpeepeepoopoorandom()peepeepoopoo->peepeepoopooHexcodepeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoofuncpeepeepoopoorandomHexDigit()peepeepoopoo->peepeepoopooDoublepeepeepoopoo{peepeepoopooDouble(Int.random(in:peepeepoopoo0peepeepoopoo...peepeepoopoo15peepeepoopoo))peepeepoopoo}
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooredComponentpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.red,peepeepoopoodigit1:peepeepoopoorandomHexDigit(),peepeepoopoodigit2:peepeepoopoorandomHexDigit())
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopoogreenComponentpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.green,peepeepoopoodigit1:peepeepoopoorandomHexDigit(),peepeepoopoodigit2:peepeepoopoorandomHexDigit())
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopooblueComponentpeepeepoopoo=peepeepoopooComponent(hexCategory:peepeepoopoo.blue,peepeepoopoodigit1:peepeepoopoorandomHexDigit(),peepeepoopoodigit2:peepeepoopoorandomHexDigit())
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooreturnpeepeepoopooHexcode(red:peepeepoopooredComponent,peepeepoopoogreen:peepeepoopoogreenComponent,peepeepoopooblue:peepeepoopooblueComponent)
 peepeepoopoo peepeepoopoo}
}

extensionpeepeepoopooHexcodepeepeepoopoo{
 peepeepoopoo peepeepoopoostaticpeepeepoopooletpeepeepoopootealpeepeepoopoo=peepeepoopooHexcode(
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoored:peepeepoopooComponent(hexCategory:peepeepoopoo.red,peepeepoopoodigit1:peepeepoopoo2,peepeepoopoodigit2:peepeepoopoo0),
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoogreen:peepeepoopooComponent(hexCategory:peepeepoopoo.green,peepeepoopoodigit1:peepeepoopoo10,peepeepoopoodigit2:peepeepoopoo0),
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooblue:peepeepoopooComponent(hexCategory:peepeepoopoo.blue,peepeepoopoodigit1:peepeepoopoo11,peepeepoopoodigit2:peepeepoopoo0)
 peepeepoopoo peepeepoopoo)
 peepeepoopoo peepeepoopoo
 peepeepoopoo peepeepoopoostaticpeepeepoopooletpeepeepoopooorangepeepeepoopoo=peepeepoopooHexcode(
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoored:peepeepoopooComponent(hexCategory:peepeepoopoo.red,peepeepoopoodigit1:peepeepoopoo12,peepeepoopoodigit2:peepeepoopoo13),
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopoogreen:peepeepoopooComponent(hexCategory:peepeepoopoo.green,peepeepoopoodigit1:peepeepoopoo8,peepeepoopoodigit2:peepeepoopoo0),
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooblue:peepeepoopooComponent(hexCategory:peepeepoopoo.blue,peepeepoopoodigit1:peepeepoopoo0,peepeepoopoodigit2:peepeepoopoo0)
 peepeepoopoo peepeepoopoo)
}
