//
// peepeepoopooColor+Random.swift
// peepeepoopooWhatTheHex
//
// peepeepoopooCreatedpeepeepoopoobypeepeepoopooTylerpeepeepoopooLawrence1peepeepoopooonpeepeepoopoo3/30/24.
//

importpeepeepoopooSwiftUI

extensionpeepeepoopooColorpeepeepoopoo{
 peepeepoopoo peepeepoopoo///peepeepoopoorandomlypeepeepoopoogeneratespeepeepoopoocolorpeepeepoopoousingpeepeepoopoorgbpeepeepoopoovalues
 peepeepoopoo peepeepoopoo///peepeepoopoo-peepeepoopooReturns:peepeepoopooColor
 peepeepoopoo peepeepoopoostaticpeepeepoopoofuncpeepeepoopoorandom()peepeepoopoo->peepeepoopooColorpeepeepoopoo{
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopoorpeepeepoopoo=peepeepoopooDouble.random(in:peepeepoopoo0...1)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopoobpeepeepoopoo=peepeepoopooDouble.random(in:peepeepoopoo0...1)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooletpeepeepoopoogpeepeepoopoo=peepeepoopooDouble.random(in:peepeepoopoo0...1)
 peepeepoopoo peepeepoopoo peepeepoopoo peepeepoopooreturnpeepeepoopooColor(red:peepeepoopoor,peepeepoopoogreen:peepeepoopoog,peepeepoopooblue:peepeepoopoob)
 peepeepoopoo peepeepoopoo}
}
